### ISSUE TITLE
Logger has hardcoded path to vishvananda's log directory

### ISSUE THREAD

**Issue by jeffhajewski** [oracle/railcar#2]
Looking through the source for logger.rs, it appears the directory specified by @vishvananda is still in there. I'm happy to submit a PR to something more generic like `/var/log` but maybe it's better to make this configurable.

**Comment by vishvananda** [comment]
ah thank you. That was leftover debugging. I will fix.

**Comment by vishvananda** [comment]
fixed in 816002b7ae802f77fd2521825a0ed87e7bf3292d
