### ISSUE TITLE
init

### ISSUE THREAD

**Issue by jcgruenhage** [oracle/railcar#3]
> Also, railcar always runs an init process separately from the container process.

Does that mean that we'll have two init processes, when the container comes with one?

**Comment by vishvananda** [comment]
If the container has its own init process, it will run as pid 2. In general this does not cause problems for the container init. Rkt has always behaved this way, for example.

**Comment by jcgruenhage** [comment]
okay.. what exactly does this pid1 process do then?

**Comment by vishvananda** [comment]
I should have been more clear. If the container has its own init process, the containers init process will run as pid 2 which will be a child of the railcar init. Init processes are generally ok running as pid 2 as long as pid 1 actually does the right things like reaping. The details of how the pid 2 init process will deal with things depend on how it is implemented, but in general it will just fork one or more child processes and sit there. This might clarify things: https://hackernoon.com/the-curious-case-of-pid-namespaces-1ce86b6bc900

**Comment by vishvananda** [comment]
Closing this for now since there is no actual issue. Feel free to reopen if you have more questions.

**Comment by jcgruenhage** [comment]
Yeah, sure. Thanks for answering :)
